/* tslint:disable */
/* eslint-disable */
export const __wbg_audioengine_free: (a: number, b: number) => void;
export const audioengine_new: (a: any, b: number, c: number, d: number, e: number) => number;
export const audioengine_set_waveform: (a: number, b: number) => void;
export const audioengine_set_stats_callback: (a: number, b: any) => void;
export const audioengine_set_note: (a: number, b: number) => void;
export const audioengine_set_frequency: (a: number, b: number) => void;
export const audioengine_set_amplitude: (a: number, b: number) => void;
export const audioengine_start: (a: number) => any;
export const audioengine_stop: (a: number) => void;
export const audioengine_get_current_frame: (a: number) => bigint;
export const main: () => void;
export const __wbg_wbg_rayon_poolbuilder_free: (a: number, b: number) => void;
export const wbg_rayon_poolbuilder_numThreads: (a: number) => number;
export const wbg_rayon_poolbuilder_receiver: (a: number) => number;
export const wbg_rayon_poolbuilder_build: (a: number) => void;
export const initThreadPool: (a: number) => any;
export const wbg_rayon_start_worker: (a: number) => void;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_export_2: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const memory: WebAssembly.Memory;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_export_7: WebAssembly.Table;
export const _dyn_core__ops__function__FnMut_____Output___R_as_wasm_bindgen__closure__WasmClosure___describe__invoke__h1fd7b879ff3e01f2: (a: number, b: number) => void;
export const closure48_externref_shim: (a: number, b: number, c: any) => void;
export const closure95_externref_shim: (a: number, b: number, c: any, d: any) => void;
export const __wbindgen_thread_destroy: (a?: number, b?: number, c?: number) => void;
export const __wbindgen_start: (a: number) => void;
